### ISSUE TITLE
Editing geospatial data with Malinki prototype/swift   MapKit

### ISSUE THREAD

**Issue by Chris98RUB** [jagodki/Malinki#1]
Hello jagodki, 

thank you for your great impressions on FOSSGIS conference of your thoughts about the importance to add a third paradigm next to web and desktop GIS for presenting and working with geospatial data. 

I am new in deeper Web and mobile GIS programming and while research, I came across with your Malinki application. 

I've never used Swift programming language before, so may you can answer a question which I am asking myself: 

Do you know if it could be possible to add an editing tool to such a map canvas, coded by swift (MapKit) respectively with Malinki, like it is possible with QGis Web Client? 

Thanks you 
Chris

**Comment by jagodki** [comment]
Hi Chris,

glad to hear that you found my talks at FOSSGIS and this (at the moment unfinished and undocumented) project 😊

At the moment, Malinki is a read-only app. Only spatial bookmarks and map pins can be added by the user and will be stored in local files on the device. The target of this app is to create access to spatial data published via OGC services to people with no GIS knowledge. The majority of people will be satisfied with reading maps instead of editing data (let's think about Google Maps).

The first version of Malinki (I hope to finish it until autumn) will be read only. But of course, it would be possible to advance the functionality of Malinki to edit data. Without spending lots of time for thinking about it, there should be 3 ways to edit data at least:
- edit a GeoJSON file on the device (problem: MapKit offers only a GeoJSON <b>DE</b>coder, an <b>EN</b>coder has to be written by myself, but that's no rocket science 😉)
- using a WFS-T
- using OGC API Features

But I am not sure, if this function is necessary, because there are a lot of closed and open source apps out there for editing spatial data, e.g. for the work force management. Could you tell me a bit more about your concerns regarding an editing capability in Malinki?

Best regards,
Christoph

**Comment by jagodki** [comment]
Closed because of inactivity. Please reopen this issue if necessary.
